number: '0123456789'
symbol: " :\\-" 
lang_char: '' 
experiment_name: '20241025_GRU_ResNet' #-----------------
train_data: 'all_data'
valid_data: 'all_data/20241025_val' #-----------------
manualSeed: 1111
workers: 8 #-----------------
batch_size: 64 #32---------------
num_iter: 455 #-----------------
valInterval: 455 #-----------------
save_interval: 455 #-----------------
saved_model: '' 
FT: False
optim: False
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: '20241025_train' #-----------------
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 19 
imgH: 32 # 64, 32, 48, 48------------------
imgW: 288 #600, 288, 416, 400-------------------
rgb: False
contrast_adjust: False
sensitive: False
PAD: False
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiGRU' #-----------------
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False